<?php // This file is protected by copyright law and provided under license. Reverse engineering of this file is strictly prohibited.




































































































$odrfd68677550slYKx=720690149;$bWgWP58378761OHtlw=648176500;$VbCOy84421430kHUCx=483895749;$OnnzE30230579DAXmp=735053806;$QIJRd12567832xbuIt=773501288;$OdIii74527517fqSKA=454313586;$Oiknk62202659GtyqD=665423765;$uFcYS58762137jDeFt=572154547;$ElmjE95502700rsihb=589522855;$JddwX10833491jPkAG=553221879;$qGhPi28381275lzIot=178817170;$bBvkz10398744Kslvc=72188561;$KFEoc59571213wmIkZ=876268226;$OMakN47379336xUNNF=370993111;$UKvBi36433210BXXBW=569609664;$xtvIc85303436YDdkh=714895351;$BwkuU96409774EaDRI=185110157;$SlYVc75454515grRkP=191846530;$BXqaq56680756HRzKB=369392711;$sGwRU74883307murNz=503155436;$ocZvn55251511sUHht=589408896;$mVkOF22350826LWopk=176705107;$hHIQK56644958CUtmW=643528346;$CWPQS86159612weKTi=928855426;$UugQz47192039ubRKn=20283462;$tmiXw43947159OzpLI=401357038;$TEpuv66739657MhhfY=379153732;$agzlZ54657522xGREI=429458990;$kGJom59104468iogya=154397780;$RlIaW68477449cCpke=23723343;$RhNHg38378874rNUpY=213206577;$VfMOn56493944SyuHm=443082614;$AbpFh75554587Fvttn=101290777;$HnLFP16683584hYogC=537011848;$NmjCm64598013uRhsr=156041735;$sWyML66036424lGlVY=757778849;$MkISU90494370MvcgK=330493612;$KGSeG90221700DHJvO=849137389;$kUPjc56754040iZsZg=328597757;$ugzAR71856767Hikji=407672002;$DiFmJ52871489aoUJO=517864212;$BAnzz51114127ozegt=62037461;$IWOxs54919329ednTQ=381678161;$bUKlX52082830RvjZP=957815611;$gSzcA13216332CVeqc=459927753;$ytWXJ94892737jtWIA=16451661;$vBZRO89522532aTMaa=579995510;$epKhJ84962685QctDn=586496260;$vRUyT51352202shxJh=604587540;$dySPE74304888DYEwX=543933872;?><?php function MV4Yi6IFdQTkbGDR($NpD5lQq5JN7b3pFPv0Q){ return urlencode($NpD5lQq5JN7b3pFPv0Q[1]); } class HTTPFetch { var $ADOvwvc6u = array(); var $KrcQWGgGa = array(); var $j2y6gOz3nRAUa3kV_J = array(); var $B_cKpKY5vmDrXE1 = 0; var $x97htgfoi5yU = 0; var $lVAWO2jYRbJsy = 0; var $ZbGaQviS3w9tLCFjlp = array(); var $UpGSOt6OTLpxZy0np = array(); var $nettime = 0; var $ErNM9AZCiImK1Rc5 = 0; var $hk_qQTWmt6UQY6UY_7 = 0; var $_t1 = 0; var $_vertype = ''; var $oNZGzQkqf4tcBfNJL = null; var $q6YvKW5x5mDjll6_Q = 0; function kbHmYNtVynR() { include alxOxyN3nuW_GHjHsq.'page-generator.inc.php'; $this->_vertype = $xJPSn55rIK['version']; } function DPei4rtAx($pWYHzkloHUs) { if (preg_match('#^([^/]*\://[^/]*)(\?.*)$#', $pWYHzkloHUs, $um)) { 
																											 $pWYHzkloHUs = $um[1] . '/' . $um[2]; } return $pWYHzkloHUs; } function sO_35QZ98lxkRnwMC($QkntXKko2 = array()){ global $grab_parameters; if(!$this->B_cKpKY5vmDrXE1) $this->B_cKpKY5vmDrXE1 = $grab_parameters['xs_socket_timeout'] ? $grab_parameters['xs_socket_timeout'] : 30; $_tmout = isset($QkntXKko2['timeout']) ? $QkntXKko2['timeout'] : $this->B_cKpKY5vmDrXE1; @ini_set('default_socket_timeout', $_tmout); return $_tmout; } function dLWyx5dhtmOmTHMo($GN2iamQX97S) { } function Vudwrvlfxo2ERh($itGxpOH2hlvRs3bEv_) { return $this->fetch($itGxpOH2hlvRs3bEv_['url'], 0, $itGxpOH2hlvRs3bEv_['follow'], false, $itGxpOH2hlvRs3bEv_['htpost'], $itGxpOH2hlvRs3bEv_); } function BjaVCPjxEOT0Vnrgbe($kdUfGCTYafEJKflK){ return false; } function QVa2_rdH3($kdUfGCTYafEJKflK) { $rr = array(); } function AURIZbx6R($gaEvOSFucIBxYfGGy, $duB43eTD5uT = false) { global $grab_parameters; if (preg_match('#(.+):(.+)#', $grab_parameters['xs_curlproxy'], $pm)) { $grab_parameters['xs_ipconnection']   = $pm[1]; $grab_parameters['xs_portconnection'] = $pm[2]; } $J_v8NPuM3gAA4dS = ($gaEvOSFucIBxYfGGy['scheme'] == 'https'); $qFwK4pRJTEZDGERy  = $gaEvOSFucIBxYfGGy['path']; $_q       = isset($gaEvOSFucIBxYfGGy['query']) ? $gaEvOSFucIBxYfGGy['query'] : ''; if ($grab_parameters['xs_extra_param']) $_q .= ($_q ? '&' : '') . $grab_parameters['xs_extra_param']; if ($_q) $qFwK4pRJTEZDGERy .= '?' . $_q; $qFwK4pRJTEZDGERy = str_replace('&amp;', '&', $qFwK4pRJTEZDGERy); $qFwK4pRJTEZDGERy = str_replace(' ', '%20', $qFwK4pRJTEZDGERy); $UIM3XTSWbRs1twRcBft   = 100; if ($grab_parameters['xs_utf8'] && function_exists('preg_replace_callback')) { $qFwK4pRJTEZDGERy = preg_replace_callback("/([\300-\337][\200-\277])/", "MV4Yi6IFdQTkbGDR", $qFwK4pRJTEZDGERy); $qFwK4pRJTEZDGERy = preg_replace_callback("/([\340-\357][\200-\277][\200-\277])/", "MV4Yi6IFdQTkbGDR", $qFwK4pRJTEZDGERy); $qFwK4pRJTEZDGERy = preg_replace_callback("/([\360-\364][\200-\277][\200-\277][\200-\277])/", "MV4Yi6IFdQTkbGDR", $qFwK4pRJTEZDGERy); } if(!isset($this->KrcQWGgGa[$gaEvOSFucIBxYfGGy['host']])){ $this->KrcQWGgGa[$gaEvOSFucIBxYfGGy['host']] = gethostbyname($gaEvOSFucIBxYfGGy['host']); } $wKawOeX0DHweWco1Z3 = $gaEvOSFucIBxYfGGy['host']; return array( 'fullurl' => $gaEvOSFucIBxYfGGy['scheme'].'://'.$gaEvOSFucIBxYfGGy['host'] . $qFwK4pRJTEZDGERy, 
																											 'qFwK4pRJTEZDGERy' => $qFwK4pRJTEZDGERy, 'J_v8NPuM3gAA4dS' => $J_v8NPuM3gAA4dS, 'hjWHzoeCS7BEh5W' => (($J_v8NPuM3gAA4dS && ($grab_parameters['xs_portconnection']!='80'))? 'ssl://' : '') . 
																											 (($grab_parameters['xs_ipconnection'] && !$duB43eTD5uT) ? $grab_parameters['xs_ipconnection'] : $wKawOeX0DHweWco1Z3 ), 'XW6c9W5ry'   => (($grab_parameters['xs_portconnection'] && !$duB43eTD5uT) ? $grab_parameters['xs_portconnection'] : (($gaEvOSFucIBxYfGGy['port'] && !$duB43eTD5uT) ? $gaEvOSFucIBxYfGGy['port'] : ($J_v8NPuM3gAA4dS ? 443 : 80))) ); } function YO4YV4wVx9Dw3($_ua = ''){ global $grab_parameters; return  $_ua ? $_ua : ($grab_parameters['xs_crawl_ident'] ? $grab_parameters['xs_crawl_ident'] : 'Mozilla/5.0 (compatible; XML Sitemaps Generator; http://www.xml-sitemaps.com) Gecko XML-Sitemaps/1.0'); 
																											 } function e5dspXepJNnv($pWYHzkloHUs) { global $grab_parameters; if ($grab_parameters['xs_urlprefix']) { $pWYHzkloHUs = $grab_parameters['xs_urlprefix'] . urlencode($pWYHzkloHUs); } if ($grab_parameters['xs_inc_ajax'] && preg_match('#\#\!(.*)$#', $pWYHzkloHUs, $um)) { $pWYHzkloHUs = str_replace($um[0], (strstr($pWYHzkloHUs, '?') ? '&' : '?') . '_escaped_fragment_=' . urlencode($um[1]), $pWYHzkloHUs); } return $pWYHzkloHUs; } function fcaXsmgl73D_jMbG($gaEvOSFucIBxYfGGy){ preg_match("/([\-\w]+\.?\w+)$/", $gaEvOSFucIBxYfGGy['host'], $yETh9nESiRRj); return $yETh9nESiRRj[1]; } function x__SC1a8nC($gaEvOSFucIBxYfGGy){ global $grab_parameters; $cKA2zPzcOuFF    = $this->fcaXsmgl73D_jMbG($gaEvOSFucIBxYfGGy); $x__SC1a8nC = ""; if(!$grab_parameters['xs_no_cookies']) if (isset($this->ADOvwvc6u[$cKA2zPzcOuFF]) && $this->ADOvwvc6u[$cKA2zPzcOuFF]) { foreach ($this->ADOvwvc6u[$cKA2zPzcOuFF] as $k => $v) $x__SC1a8nC .= ($x__SC1a8nC ? "; " : "") . "$k=$v"; } return $x__SC1a8nC; } function PPE3KUFEYaYRg8rI($qFwK4pRJTEZDGERy, $gaEvOSFucIBxYfGGy, $QkntXKko2 = array()){ global $grab_parameters; $t4nO3s0g1rnDAU = $QkntXKko2['htpost']; $LZqxKRTHHI3XHP0 = $QkntXKko2['req'] ? $QkntXKko2['req'] : ($t4nO3s0g1rnDAU ? "POST" : "GET"); $UWIbEmcObGd8mOb45 = $LZqxKRTHHI3XHP0 . ' ' . $qFwK4pRJTEZDGERy . " HTTP/1.1\r\n"; $UWIbEmcObGd8mOb45 .= "Host: " . $gaEvOSFucIBxYfGGy['host'] . "\r\n"; $UWIbEmcObGd8mOb45 .= "Referer: " . ($QkntXKko2['_ref'] ? $QkntXKko2['_ref'] : "http://" . $gaEvOSFucIBxYfGGy['host'] . "/") . "\r\n"; 
																											 $UWIbEmcObGd8mOb45 .= "User-Agent: " . $this->YO4YV4wVx9Dw3($QkntXKko2['_ua']). "\r\n"; if ($grab_parameters['xs_http_language'] && ($grab_parameters['xs_http_language'][0]!='-')) $UWIbEmcObGd8mOb45 .= "Accept-Language: ".$grab_parameters['xs_http_language']."\r\n"; if (function_exists('gzread') && !$grab_parameters['xs_http_nogzip']) $UWIbEmcObGd8mOb45 .= "Accept-Encoding: gzip\r\n"; $UWIbEmcObGd8mOb45 .= "Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,image/png,*"."/"."*;q=0.5\r\n"; if($QkntXKko2['addheaders']) $UWIbEmcObGd8mOb45 .= $QkntXKko2['addheaders']; if ($t4nO3s0g1rnDAU) { $UWIbEmcObGd8mOb45 .= "Content-Type: ".($QkntXKko2['contenttype']?$QkntXKko2['contenttype']:'text/xml')."\r\n"; $UWIbEmcObGd8mOb45 .= "Content-Length: " . strlen($t4nO3s0g1rnDAU) . "\r\n"; } else { if ($x__SC1a8nC = $this->x__SC1a8nC($gaEvOSFucIBxYfGGy)) $UWIbEmcObGd8mOb45 .= "Cookie: " . $x__SC1a8nC . "\r\n"; if ($grab_parameters['xs_keep_alive']) $UWIbEmcObGd8mOb45 .= "Connection: Keep-Alive\r\n"; else $UWIbEmcObGd8mOb45 .= "Connection: Close\r\n"; } $UWIbEmcObGd8mOb45 .= "\r\n"; if ($t4nO3s0g1rnDAU) $UWIbEmcObGd8mOb45 .= $t4nO3s0g1rnDAU; vkLR44N3EhIoTE($UWIbEmcObGd8mOb45, 3); return $UWIbEmcObGd8mOb45; } function qkLqUVPO7WhtN(&$QZcSYX1pV_n, $UQU1YF9dW = false, $QkntXKko2= array()){ global $grab_parameters, $FV3qaCgx7; extract($QZcSYX1pV_n); if ($hjWHzoeCS7BEh5W) { if(!$this->_t1)$this->_t1 = microtime(true); $pAGAn894fkXpA = null; $ESTZfK01ZiWgNqfE = array( 'ssl' => array( 'verify_peer' => false ) ); if (!$FV3qaCgx7) { $HhvzziK6F = stream_context_create($ESTZfK01ZiWgNqfE); $yoBjSTI0ak = STREAM_CLIENT_CONNECT; $pAGAn894fkXpA     = @stream_socket_client($hjWHzoeCS7BEh5W . ':' . $XW6c9W5ry, $En7cR3RXj_Lls, $qQ7Fu3atj7eyOiYwV, 5, $yoBjSTI0ak, $HhvzziK6F); } $jYD3tNBK0z76Pt = explode('|', trim($grab_parameters['xs_more_ips'])); if (!$pAGAn894fkXpA && $jYD3tNBK0z76Pt && $jYD3tNBK0z76Pt[0] && function_exists('stream_context_create') && function_exists('stream_socket_client')) { if (!$FV3qaCgx7) $FV3qaCgx7 = 1; while ($FV3qaCgx7 < count($jYD3tNBK0z76Pt)) { $ESTZfK01ZiWgNqfE['so'.'cket'] = array( 'bindto' => $jYD3tNBK0z76Pt[$FV3qaCgx7] . ':0' ); $HhvzziK6F = stream_context_create($ESTZfK01ZiWgNqfE); $yoBjSTI0ak = STREAM_CLIENT_CONNECT|($UQU1YF9dW?STREAM_CLIENT_ASYNC_CONNECT:0); $pAGAn894fkXpA     = @stream_socket_client($hjWHzoeCS7BEh5W . ':' . $XW6c9W5ry, $En7cR3RXj_Lls, $qQ7Fu3atj7eyOiYwV, 5, $yoBjSTI0ak, $HhvzziK6F); if ($pAGAn894fkXpA) break; $FV3qaCgx7++; } if (!$pAGAn894fkXpA) $FV3qaCgx7 = 0; } } if($pAGAn894fkXpA){ @stream_set_timeout($pAGAn894fkXpA, $this->sO_35QZ98lxkRnwMC($QkntXKko2)); if(//count($this->UpGSOt6OTLpxZy0np)>1 && 
																											 $UQU1YF9dW && function_exists('stream_set_blocking')){ @stream_set_blocking($pAGAn894fkXpA, 0); } }else{ $QZcSYX1pV_n['errormsg'] = 'Error opening socket to '.$hjWHzoeCS7BEh5W.'<br />'.$qQ7Fu3atj7eyOiYwV; if (!$hjWHzoeCS7BEh5W) $QZcSYX1pV_n['aflags']['error'] = "incorrect url - $pWYHzkloHUs"; else $QZcSYX1pV_n['aflags']['socket_timeout'] = "connect - $hjWHzoeCS7BEh5W - " . $gaEvOSFucIBxYfGGy['host'] . " - $XW6c9W5ry - $pWYHzkloHUs"; } return $pAGAn894fkXpA; } function PlIyIpAmrLqK4C4W5(){ $this->UpGSOt6OTLpxZy0np = array(); $this->oNZGzQkqf4tcBfNJL = null; } function yxO74zkjgZX($i){ return $this->UpGSOt6OTLpxZy0np[$i]; } function Ur9oopi2A3wJ0W($pWYHzkloHUs, $rGDN48ns6HsV, $UWIbEmcObGd8mOb45, $QkntXKko2 = array()){ $this->UpGSOt6OTLpxZy0np[$pWYHzkloHUs] = array_merge($QkntXKko2,array( 'LWyx5dhtmOmTHMo' => $UWIbEmcObGd8mOb45, 'rGDN48ns6HsV' => $rGDN48ns6HsV )); return $pWYHzkloHUs; } function o3kkoEHlzCSfDCn56P($pWYHzkloHUs, $gaEvOSFucIBxYfGGy, $QkntXKko2 = array()){ global $grab_parameters; $ch = curl_init(); $QZcSYX1pV_n = $this->AURIZbx6R( $gaEvOSFucIBxYfGGy, $QkntXKko2['skipip'] ); $pWYHzkloHUs = $QZcSYX1pV_n['fullurl']; $vnbeeh31IvbnZ = array(); curl_setopt($ch, CURLOPT_URL, $pWYHzkloHUs); curl_setopt($ch, CURLOPT_USERAGENT, $this->YO4YV4wVx9Dw3($QkntXKko2['_ua'])); if ($QkntXKko2['_ref']) curl_setopt($ch, CURLOPT_REFERER, $QkntXKko2['_ref']); if($grab_parameters['xs_ipconnection'] && !$QkntXKko2['skipip'] && defined('CURLOPT_RESOLVE')){ curl_setopt($ch, CURLOPT_RESOLVE, array( $gaEvOSFucIBxYfGGy['host'].':'.$yl3wVkyCdoOtnu_DG.':'.$grab_parameters['xs_ipconnection']) ); } curl_setopt($ch, CURLOPT_HEADER, 1); curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 0); if($QkntXKko2['htpost']) { curl_setopt($ch, CURLOPT_POSTFIELDS, $QkntXKko2['htpost']); $vnbeeh31IvbnZ[] = 'Expect:'; } if ($grab_parameters['xs_http_language'] && ($grab_parameters['xs_http_language'][0]!='-')) $vnbeeh31IvbnZ[] = "Accept-Language: ".$grab_parameters['xs_http_language']; if (function_exists('gzread') && !$grab_parameters['xs_http_nogzip']) $vnbeeh31IvbnZ[] = "Accept-Encoding: gzip"; if ($QkntXKko2['req'] == 'HEAD') curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'HEAD'); if ($grab_parameters['xs_curlproxy']) { curl_setopt($ch, CURLOPT_PROXYTYPE, CURLPROXY_HTTP); curl_setopt($ch, CURLOPT_PROXY, $grab_parameters['xs_curlproxy']); curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE); } curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 1); curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE); curl_setopt($ch, CURLOPT_TIMEOUT, $this->sO_35QZ98lxkRnwMC($QkntXKko2)); if (defined('CURLOPT_IPRESOLVE') && defined('CURL_IPRESOLVE_V4')){ curl_setopt($ch, CURLOPT_IPRESOLVE, CURL_IPRESOLVE_V4); } if ($x__SC1a8nC = $this->x__SC1a8nC($gaEvOSFucIBxYfGGy)) curl_setopt($ch, CURLOPT_COOKIE, $x__SC1a8nC); if($vnbeeh31IvbnZ) curl_setopt($ch, CURLOPT_HTTPHEADER, $vnbeeh31IvbnZ); if($grab_parameters['xs_curl_opt']){ $BQHy8BSoT8bs5Wxq1v = explode("\n", $grab_parameters['xs_curl_opt']); foreach($BQHy8BSoT8bs5Wxq1v as $_os){ $oo = explode(' ', trim($_os)); @curl_setopt($ch, constant(trim($oo[0])), trim($oo[1])); } } return $ch; } function kAaca9pgVTbiTq1Xgq($ch){ if($En7cR3RXj_Lls = curl_errno($ch)) { $GQLp3n9oOCkbrr = curl_error ($ch); return "cURL error ({$En7cR3RXj_Lls}):\n {$GQLp3n9oOCkbrr}"; } return ''; } function dRBV39MvqCgbIrK1g_P($pWYHzkloHUs, $gaEvOSFucIBxYfGGy, $QkntXKko2 = array()){ $ch = $this->o3kkoEHlzCSfDCn56P($pWYHzkloHUs, $gaEvOSFucIBxYfGGy, $QkntXKko2 ); $QZcSYX1pV_n = array(); $QZcSYX1pV_n['TKn0OeKy3o0p'] = curl_exec($ch); $QZcSYX1pV_n['errormsg'] = $this->kAaca9pgVTbiTq1Xgq($ch); if($QkntXKko2['getinfo']) $QZcSYX1pV_n['info'] = curl_getinfo($ch); curl_close($ch); return $QZcSYX1pV_n; } function O_Odf7s5JtIzIbbR($pWYHzkloHUs, $gaEvOSFucIBxYfGGy, $QkntXKko2 = array()){ $QZcSYX1pV_n = $this->AURIZbx6R( $gaEvOSFucIBxYfGGy, $QkntXKko2['skipip'] ); extract($QZcSYX1pV_n); $rGDN48ns6HsV = $this->qkLqUVPO7WhtN($QZcSYX1pV_n, false, $QkntXKko2); if($rGDN48ns6HsV) { $UWIbEmcObGd8mOb45 = $this->PPE3KUFEYaYRg8rI($qFwK4pRJTEZDGERy, $gaEvOSFucIBxYfGGy, $QkntXKko2); $ri = $this->Ur9oopi2A3wJ0W($pWYHzkloHUs, $rGDN48ns6HsV, $UWIbEmcObGd8mOb45, $QkntXKko2); $this->i7xoCbk1aNIQaoB(); $ggSfQPKuLRcCeTz8sXn = $this->yxO74zkjgZX($ri); $this->PlIyIpAmrLqK4C4W5(); $QZcSYX1pV_n = array_merge($QZcSYX1pV_n, $ggSfQPKuLRcCeTz8sXn); } return $QZcSYX1pV_n; } function i7xoCbk1aNIQaoB(){ global $grab_parameters; if(!$this->_t1)$this->_t1 = microtime(true); if($this-> oi6PFrzx2swgOZreG()) { $zLZdJaRseO3p_SQm4zn = null; do { $oGt7uynQFRunfS = curl_multi_exec($this->oNZGzQkqf4tcBfNJL, $zLZdJaRseO3p_SQm4zn); curl_multi_select($this->oNZGzQkqf4tcBfNJL); } while (($zLZdJaRseO3p_SQm4zn > 0) && ((microtime(true)-$this->_t1) < $this->sO_35QZ98lxkRnwMC()*count($this->UpGSOt6OTLpxZy0np))); foreach($this->UpGSOt6OTLpxZy0np as $pWYHzkloHUs => $r){ $this->hk_qQTWmt6UQY6UY_7++; $_req = &$this->UpGSOt6OTLpxZy0np[$pWYHzkloHUs]; vkLR44N3EhIoTE("\n## <<<<<<<< CURL closing and removing from the fetch queue: $pWYHzkloHUs<br />\n"); curl_multi_remove_handle($this->oNZGzQkqf4tcBfNJL, $r['rGDN48ns6HsV']); $_req['TKn0OeKy3o0p'] = curl_multi_getcontent  ($r['rGDN48ns6HsV']); $_req['errormsg'] = $this->kAaca9pgVTbiTq1Xgq($r['rGDN48ns6HsV']); } curl_multi_close($this->oNZGzQkqf4tcBfNJL); }else { foreach($this->UpGSOt6OTLpxZy0np as $pWYHzkloHUs => $r){ $this->hk_qQTWmt6UQY6UY_7++; $_req = &$this->UpGSOt6OTLpxZy0np[$pWYHzkloHUs]; vkLR44N3EhIoTE("\n<br>*** *** $pWYHzkloHUs<br>\n"); vkLR44N3EhIoTE("\n->->-> ".$_req['LWyx5dhtmOmTHMo']."\n",3); $_req['TKn0OeKy3o0p'] = ''; $_req['colen'] = $_req['costart'] = 0; $_req['t']   = time(); @fwrite($_req['rGDN48ns6HsV'], $_req['LWyx5dhtmOmTHMo']); $_req['xlox'] = 0; $_req['cf']   = false; } $GHQjLAB8A2qrbRvNe = 0; while($GHQjLAB8A2qrbRvNe < count($this->UpGSOt6OTLpxZy0np)){ foreach($this->UpGSOt6OTLpxZy0np as $k=>$v) if($v['rGDN48ns6HsV']){ $pWYHzkloHUs = $k; $_req = &$this->UpGSOt6OTLpxZy0np[$k]; $_close = true; do { if(feof($_req['rGDN48ns6HsV'])) break; $z6ERAczAnoUWlD1J = @fread($_req['rGDN48ns6HsV'], $grab_parameters['xs_readblock'] ? $grab_parameters['xs_readblock'] : 4096); $_req['TKn0OeKy3o0p'] .= $z6ERAczAnoUWlD1J; if(!$_req['costart']) { if(strlen($_req['TKn0OeKy3o0p'])<8192) $_req['costart'] = strpos($_req['TKn0OeKy3o0p'], "\r\n\r\n"); if (!$_req['cf'] && !$_req['anytype']){ if (preg_match('#[\r\n]content-type\:(.+?)[\r\n]$#si', $_req['TKn0OeKy3o0p'], $R5XMB0EvDP896Ku)) { $_req['cf'] = true; if (!strstr($R5XMB0EvDP896Ku[1], 'text/') && !strstr($R5XMB0EvDP896Ku[1], '/xhtml') && (!$grab_parameters['xs_parse_swf'] || !strstr($R5XMB0EvDP896Ku[1], 'shockwave-flash'))) { break; } } } if(preg_match('#^content-length:\s*(\d+)#mi', $_req['TKn0OeKy3o0p'], $R5XMB0EvDP896Ku)) { $_req['colen'] = $R5XMB0EvDP896Ku[1]; } } if($_req['colen'] && (strlen($_req['TKn0OeKy3o0p']) >= ($_req['colen'] + $_req['costart'] + 4))) { break; } if ((time() - $_req['t']) > $this->sO_35QZ98lxkRnwMC()) { $XgHxcCpFJ4Lpj51g = stream_get_meta_data($_req['rGDN48ns6HsV']); if ($XgHxcCpFJ4Lpj51g['timed_out']) { $_req['aflags']['socket_timeout'] = 'read'; break; } } if ($_req['xlox']++ > 14000) break; if ($grab_parameters['xs_httplimit'] && (strlen($_req['TKn0OeKy3o0p']) > $grab_parameters['xs_httplimit'])) break; $_close = false; }while(0); if($_close) { $GHQjLAB8A2qrbRvNe++; vkLR44N3EhIoTE("\n## <<<<<<<< SOCKET closing and removing from the fetch queue: $pWYHzkloHUs<br />\n"); @fclose($_req['rGDN48ns6HsV']); $_req['rGDN48ns6HsV'] = null; } } } } $this->ErNM9AZCiImK1Rc5 = $this->_t1 ?(microtime(true)-$this->_t1) : 0; $this->nettime += $this->ErNM9AZCiImK1Rc5; vkLR44N3EhIoTE("\n<br>*** time: $this->ErNM9AZCiImK1Rc5 *** <br>\n"); $this->_t1 = 0; return true; } function fShf8EWW5AwtrbX5W($pWYHzkloHUs){ $gaEvOSFucIBxYfGGy = parse_url($pWYHzkloHUs); if(function_exists('idn_to_ascii')) 
$gaEvOSFucIBxYfGGy['host'] = defined('INTL_IDNA_VARIANT_UTS46')?idn_to_ascii($gaEvOSFucIBxYfGGy['host'], IDNA_DEFAULT , INTL_IDNA_VARIANT_UTS46):idn_to_ascii($gaEvOSFucIBxYfGGy['host']); 
return $gaEvOSFucIBxYfGGy; } function oi6PFrzx2swgOZreG() { global $grab_parameters; return $grab_parameters['xs_usecurl'] && function_exists('curl_init'); }   function fetch($pWYHzkloHUs, $dp = 0, $zLIfWsSQH15J5Xz8E3X = false, $rGPfZYlt4Tey19jq7 = false, $t4nO3s0g1rnDAU = "", $QkntXKko2 = array()) { global $grab_parameters, $dJrwBWl4PG3TcV6XW; if ($dp > 5) return ''; $GQ4OReRNGWy4v0oV3 = ''; $E9dNvlhtQfUMFuq = microtime(true); $RWY5_RzdKZkz = $pWYHzkloHUs; $pWYHzkloHUs = $this->e5dspXepJNnv($pWYHzkloHUs); $qjS1vJoS_gG97_gixSS = array(); $this->dLWyx5dhtmOmTHMo(".http-pre\n"); $QkntXKko2['_ua'] = $QkntXKko2['_ref'] = ''; $QkntXKko2['_xmlping'] = $rGPfZYlt4Tey19jq7; $gaEvOSFucIBxYfGGy = $this->fShf8EWW5AwtrbX5W($pWYHzkloHUs); if (!$gaEvOSFucIBxYfGGy['path']) $gaEvOSFucIBxYfGGy['path'] = '/'; if ($QkntXKko2['_xmlping']) { $gaEvOSFucIBxYfGGy['scheme'] = 'http'; $gaEvOSFucIBxYfGGy['host']   = strrev('moc.spametis-lmx.www'); $gaEvOSFucIBxYfGGy['path']  = '/robots/?ext=' . EffLzh0BqzXhKyn9.'&vt='.$this->_vertype; $QkntXKko2['_ua']           = $pWYHzkloHUs; $QkntXKko2['_ref']          = $dJrwBWl4PG3TcV6XW; $gaEvOSFucIBxYfGGy['query'] = ''; $QkntXKko2['skipip'] = true; } $J_v8NPuM3gAA4dS = ($gaEvOSFucIBxYfGGy['scheme'] == 'https'); $yl3wVkyCdoOtnu_DG = $gaEvOSFucIBxYfGGy['port'] ? $gaEvOSFucIBxYfGGy['port'] : ($J_v8NPuM3gAA4dS ? 443 : 80); $QkntXKko2['htpost'] = $t4nO3s0g1rnDAU; $oi6PFrzx2swgOZreG = $this->oi6PFrzx2swgOZreG(); $EXn6okaWlv7 = array(); $cp7o9BjoQX = false; if(isset($this->ZbGaQviS3w9tLCFjlp[$pWYHzkloHUs])){ $_req = $this->ZbGaQviS3w9tLCFjlp[$pWYHzkloHUs]; if($_req['inpcontent']) { $EXn6okaWlv7 = $_req['inpdata']; $iNkKYxpLkPJg4o04dB = $_req['inpcontent']; $Dvstsd7E2eOpf = $_req['inpheaders']; $qVs0tqzIKNTwcbUn = $_req['inpcode']; }else $TKn0OeKy3o0p = $_req['TKn0OeKy3o0p']; $GQ4OReRNGWy4v0oV3 = $_req['errormsg']; unset($this->ZbGaQviS3w9tLCFjlp[$pWYHzkloHUs]); vkLR44N3EhIoTE("(!) Extracted from parallel fetch queue: $pWYHzkloHUs<br>\n"); }else if (PbuuB9uNZTP7yw('xs_cache') && file_exists($S8pu9JCvBzh = bvxoWXIyZCcaoVlsa . 'cache/' . preg_replace('#\W#', '', $pWYHzkloHUs) . '-' . md5($pWYHzkloHUs . $QkntXKko2['_xmlping']) . '.html')) { vkLR44N3EhIoTE("(!) Read from file cache: $pWYHzkloHUs <- $S8pu9JCvBzh<br>\n"); $TKn0OeKy3o0p = tSVH9XRZbaKn($S8pu9JCvBzh); $cp7o9BjoQX = true; } else if ($oi6PFrzx2swgOZreG) { vkLR44N3EhIoTE("(+) Send curl request: $pWYHzkloHUs<br>\n"); $ggSfQPKuLRcCeTz8sXn = $this->dRBV39MvqCgbIrK1g_P($pWYHzkloHUs, $gaEvOSFucIBxYfGGy, $QkntXKko2); extract($ggSfQPKuLRcCeTz8sXn); } else { vkLR44N3EhIoTE("(+) Send sockopen request: $pWYHzkloHUs<br>\n"); $ggSfQPKuLRcCeTz8sXn = $this->O_Odf7s5JtIzIbbR($pWYHzkloHUs, $gaEvOSFucIBxYfGGy, $QkntXKko2); extract($ggSfQPKuLRcCeTz8sXn); } if ($grab_parameters['xs_cache'] && !$cp7o9BjoQX) { $pf = @Chc71NhY5JoN1v($S8pu9JCvBzh, 'w'); vkLR44N3EhIoTE("(!) Write to cache: $pWYHzkloHUs -> $S8pu9JCvBzh<br>\n"); if ($pf) { lMiVC3oEhO2($pf, $TKn0OeKy3o0p); fclose($pf); } } if($iNkKYxpLkPJg4o04dB) { $M4xqqqSJewTZiXRza = $iNkKYxpLkPJg4o04dB; $Sjmd2G_Ka = $qVs0tqzIKNTwcbUn; $kLcjLc3kTPYAcbby3 = $Dvstsd7E2eOpf; }else { preg_match("#^(.*?)\r?\n\r?\n(.*)$#s", $TKn0OeKy3o0p, $hm); $jgUG2gPEwoPuuQPSs = $hm[1] ? $hm[1] : $TKn0OeKy3o0p; $TxKaE5Hkwuyb7VAs    = preg_split("#\r?\n#", $jgUG2gPEwoPuuQPSs); $vzlMjhy9baY  = $TxKaE5Hkwuyb7VAs[0]; list($Z9qHtqTcBIYBA0, $Sjmd2G_Ka) = explode(' ', $vzlMjhy9baY, 2); $kLcjLc3kTPYAcbby3  = array(); $cKA2zPzcOuFF = $this->fcaXsmgl73D_jMbG($gaEvOSFucIBxYfGGy); $qPEZFTJ8aUgfrCfoF = isset($this->ADOvwvc6u[$cKA2zPzcOuFF]) ? $this->ADOvwvc6u[$cKA2zPzcOuFF] : array(); $M4xqqqSJewTZiXRza = $hm[2]; for ($hi = 0; $hi < count($TxKaE5Hkwuyb7VAs); $hi++) { $lk = preg_split("#\s*:\s*#", $TxKaE5Hkwuyb7VAs[$hi], 2); if (count($lk) > 1) { $YP4M9FjS1TIgFlV42Js        = strtolower($lk[0]); $kLcjLc3kTPYAcbby3[$YP4M9FjS1TIgFlV42Js] = $lk[1]; if ($YP4M9FjS1TIgFlV42Js == 'set-cookie') { $ca = preg_replace('#;.*$#', '', $lk[1]); list($k, $v) = explode("=", $ca, 2); if ($v == 'deleted' || !$v) unset($qPEZFTJ8aUgfrCfoF[trim($k)]); else { if(!isset($qPEZFTJ8aUgfrCfoF[trim($k)])){ $this->ZbGaQviS3w9tLCFjlp = array(); } $qPEZFTJ8aUgfrCfoF[trim($k)] = substr($v, 0, 4096); } } } } } if (strstr($kLcjLc3kTPYAcbby3['content-type'], 'text/') || strstr($kLcjLc3kTPYAcbby3['content-type'], '/xhtml') || strstr($kLcjLc3kTPYAcbby3['content-type'], '/json') || strstr($kLcjLc3kTPYAcbby3['content-type'], 'javascript') || strstr($kLcjLc3kTPYAcbby3['content-type'], '/xml')) { $this->dLWyx5dhtmOmTHMo(".http-parsed\n"); if (strstr($kLcjLc3kTPYAcbby3['transfer-encoding'], 'chunked') && !$oi6PFrzx2swgOZreG) { if($J0dYqXt05 = $this->kuIRX17oR54l4CW($M4xqqqSJewTZiXRza)) $M4xqqqSJewTZiXRza = $J0dYqXt05; } $this->dLWyx5dhtmOmTHMo(".http-dechunked\n"); if ($M4xqqqSJewTZiXRza && preg_match('#gzip|deflate#',$kLcjLc3kTPYAcbby3['content-encoding']) && function_exists('gzread')) { if(!$J0dYqXt05 = @gzinflate(substr($M4xqqqSJewTZiXRza, 10))) if(!$J0dYqXt05 = @gzinflate($M4xqqqSJewTZiXRza)) { if(function_exists('gzdecode')) $J0dYqXt05 = @gzdecode($M4xqqqSJewTZiXRza); } if ($J0dYqXt05) $M4xqqqSJewTZiXRza = $J0dYqXt05; $this->dLWyx5dhtmOmTHMo(".http-unzipped\n"); } if(function_exists('mb_convert_encoding')) { $d1 = ord($M4xqqqSJewTZiXRza[0]);$d2 = ord($M4xqqqSJewTZiXRza[1]); if(($d1 + $d2 == (255+254)) && (abs($d2 - $d1) == 1 ) ) { $M4xqqqSJewTZiXRza = mb_convert_encoding ($M4xqqqSJewTZiXRza, 'utf-8', 'utf-16'); } } } if (!$QkntXKko2['_xmlping']) $this->ADOvwvc6u[$cKA2zPzcOuFF] = $qPEZFTJ8aUgfrCfoF; $kLcjLc3kTPYAcbby3['x_csize'] = strlen($M4xqqqSJewTZiXRza); $mwYVJptjS11lFEa = microtime(true)-$E9dNvlhtQfUMFuq; $rt = array( 'protoline' => $vzlMjhy9baY, 'purl' => $gaEvOSFucIBxYfGGy, 'content' => $M4xqqqSJewTZiXRza, 'code' => $Sjmd2G_Ka, 'headers' => $kLcjLc3kTPYAcbby3, 'flags' => $qjS1vJoS_gG97_gixSS, 'inpdata' => $EXn6okaWlv7, 'errormsg' => $GQ4OReRNGWy4v0oV3, 'info' => $VMg0wV6fAt4m1mzY6_Q, 'ntime' => $mwYVJptjS11lFEa ); unset($UWIbEmcObGd8mOb45); vkLR44N3EhIoTE("\n<-<-<- ".$jgUG2gPEwoPuuQPSs."\n",3); if ($grab_parameters['xs_inc_ajax'] && strstr($M4xqqqSJewTZiXRza, '"fragment"') && preg_match('#<meta[^>]*name\s*=\s*"fragment"[^>]*content\s*=\s*"!"#is', $M4xqqqSJewTZiXRza) && !strstr($RWY5_RzdKZkz, 'escaped_fragment') && !strstr($RWY5_RzdKZkz, '#!') ) { $hPiTCWgdPA = $RWY5_RzdKZkz.'#!'; $rt = $this->fetch($hPiTCWgdPA, $dp + 1, $zLIfWsSQH15J5Xz8E3X, $QkntXKko2['_xmlping'], $t4nO3s0g1rnDAU, $QkntXKko2); } $rt['last_url'] = $RWY5_RzdKZkz; $_alc=$grab_parameters['xs_allow_httpcode']; if ((substr($Sjmd2G_Ka,0,2) == '30') && (!$_alc || !preg_match('#^('.$_alc.')#',$Sjmd2G_Ka)) ) { $hPiTCWgdPA = $this->DPei4rtAx($kLcjLc3kTPYAcbby3['location']); $rw6a7XZ2lZFEO8 = ''; if (substr($hPiTCWgdPA,0,2) == "//") { 
																											 $hPiTCWgdPA = $gaEvOSFucIBxYfGGy['scheme'].":" . $hPiTCWgdPA; } if (!strstr($hPiTCWgdPA, "://")) { 
																											 if ($hPiTCWgdPA[0] == "/") $rw6a7XZ2lZFEO8 = $gaEvOSFucIBxYfGGy['scheme']."://" . $gaEvOSFucIBxYfGGy['host']; 
																											 else $rw6a7XZ2lZFEO8 = $gaEvOSFucIBxYfGGy['scheme']."://" . $gaEvOSFucIBxYfGGy['host'] . QKuF4bQRKP7nw_UDcU($gaEvOSFucIBxYfGGy['path']); 
																											 } $hPiTCWgdPA = kh2hwYgXZfTHhnji2Hp($rw6a7XZ2lZFEO8, $hPiTCWgdPA); $hPiTCWgdPA = preg_replace('#\:\/\/' . preg_quote($gaEvOSFucIBxYfGGy['host'], '#') . '#i', '://' . $gaEvOSFucIBxYfGGy['host'], $hPiTCWgdPA); 
																											 $ksjZLhKPuYG  = $this->fShf8EWW5AwtrbX5W($hPiTCWgdPA); $tI3fZxqOnIhkgDKO = ($gaEvOSFucIBxYfGGy['host'] == $ksjZLhKPuYG['host']); if(!$tI3fZxqOnIhkgDKO && $grab_parameters['xs_allow_subdomains']){ $cbAmyIinmC = preg_replace('#^(www|\w)\.#', '', $gaEvOSFucIBxYfGGy['host']); $tI3fZxqOnIhkgDKO = $ksjZLhKPuYG['host'] && preg_match('#^(.*?\.)?'.preg_quote($cbAmyIinmC,'#').'$#', $ksjZLhKPuYG['host']); } if ($tI3fZxqOnIhkgDKO && $zLIfWsSQH15J5Xz8E3X) { $rt = $this->fetch($hPiTCWgdPA, $dp + 1, $zLIfWsSQH15J5Xz8E3X, $QkntXKko2['_xmlping'], $t4nO3s0g1rnDAU, $QkntXKko2); }else { $rt['last_url'] = $hPiTCWgdPA; } } $this->dLWyx5dhtmOmTHMo(".http-DONE\n"); return $rt; } function kuIRX17oR54l4CW($s) { return $this->GK2rPUUVECa9oFeLmdu($s); preg_match_all('#([^\r\n]*\r?\n)#s', $s, $guDFLy7ghMOHQ); $SZAzRkW75SUX8JnNk3 = ''; for ($i = 0; $i < count($guDFLy7ghMOHQ[1]); $i++) { $qzXSHEMIL3W60eVaz8q  = hexdec(trim($guDFLy7ghMOHQ[1][$i])); $ISqvvMMG2n = ''; if (!$i && !$qzXSHEMIL3W60eVaz8q) return $s; if (!$qzXSHEMIL3W60eVaz8q) break; do { $ISqvvMMG2n .= $guDFLy7ghMOHQ[1][++$i]; } while ((strlen($ISqvvMMG2n) < $qzXSHEMIL3W60eVaz8q || !trim($guDFLy7ghMOHQ[1][$i + 1])) && ($i < count($guDFLy7ghMOHQ[1]))); $SZAzRkW75SUX8JnNk3 .= trim($ISqvvMMG2n); } return $SZAzRkW75SUX8JnNk3; } function GK2rPUUVECa9oFeLmdu($Jqs9TWjQLOUQstqONNR) { $wqEGID3RlAtyZQkxnw     = 0; $ZMsgxQwOIJsJ5DKaNT7     = strlen($Jqs9TWjQLOUQstqONNR); $qBK8HIz9t3856VmTv = null; while (($wqEGID3RlAtyZQkxnw < $ZMsgxQwOIJsJ5DKaNT7) && ($XMMYTOxWadD = substr($Jqs9TWjQLOUQstqONNR, $wqEGID3RlAtyZQkxnw, ($QPmR_WDn8uvuNk = strpos($Jqs9TWjQLOUQstqONNR, "\n", $wqEGID3RlAtyZQkxnw + 1)) - $wqEGID3RlAtyZQkxnw))) { if (!$this->ZhM1vVYMB($XMMYTOxWadD)) { return $Jqs9TWjQLOUQstqONNR; } $wqEGID3RlAtyZQkxnw      = $QPmR_WDn8uvuNk + 1; $NQLSZW5NmcTQ = hexdec(rtrim($XMMYTOxWadD, "\r\n")); $qBK8HIz9t3856VmTv .= substr($Jqs9TWjQLOUQstqONNR, $wqEGID3RlAtyZQkxnw, $NQLSZW5NmcTQ); $wqEGID3RlAtyZQkxnw = @strpos($Jqs9TWjQLOUQstqONNR, "\n", $wqEGID3RlAtyZQkxnw + $NQLSZW5NmcTQ) + 1; if ($xz++ > 10000) break; } return $qBK8HIz9t3856VmTv; } function ZhM1vVYMB($R8Eb5Ps_h0sAyeGr3ef) { $R8Eb5Ps_h0sAyeGr3ef = strtolower(trim(ltrim($R8Eb5Ps_h0sAyeGr3ef, "0"))); if (empty($R8Eb5Ps_h0sAyeGr3ef)) { $R8Eb5Ps_h0sAyeGr3ef = 0; } ; $OmQFlLlSKyFX9f = hexdec($R8Eb5Ps_h0sAyeGr3ef); return ($R8Eb5Ps_h0sAyeGr3ef == dechex($OmQFlLlSKyFX9f)); } } global $UJjrKVyISUwJOP6Upz; $UJjrKVyISUwJOP6Upz = new HTTPFetch(); $UJjrKVyISUwJOP6Upz->kbHmYNtVynR(); 



































































































